# Generated by Django 4.2 on 2025-05-21 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_time", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "activity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transportation", "Transportation"),
                            ("accommodation", "Accommodation"),
                            ("sightseeing", "Sightseeing"),
                            ("food", "Food & Dining"),
                            ("entertainment", "Entertainment"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["date_time"],
            },
        ),
    ]
