# Generated by Django 4.2 on 2025-05-21 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("temperature", models.FloatField()),
                ("conditions", models.CharField(max_length=100)),
                ("forecast", models.TextField()),
                ("retrieved_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
                "ordering": ["-retrieved_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="weatherdata",
            constraint=models.UniqueConstraint(
                fields=("location", "retrieved_at"), name="unique_location_time"
            ),
        ),
    ]
